import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

function Contact() {
  return (
    <div>
      <h1 className="">Contact</h1>
    </div>
  );
}

export default Contact;
