import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "product",
  description: "Generated by create next app",
};

import Link from "next/link";
function page() {
  return (
    <div>
      <h1>
        <Link href="/page">product</Link>
      </h1>
    </div>
  );
}

export default page;
